language: python

python:
  - '3.4'
services:
  - postgresql
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install coveralls
before_script:
  - cd app/tests
  - psql -c 'create database stack;' -U postgres
  -database.yml.travis config
script:
  - pytest
  - pytest --cov-report term-missing --cov=app
  - pytest --cov=.
  

after_success:
  - coveralls

cache: pip
